name: Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Build
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    on:
      # Trigger the workflow on push or pull request,
      # but only for the main branch
    push:
    branches:
      - main
  pull_request:
    branches:
      - main
    - name: Setup Java
      uses: actions/setup-java@v1
      with:
        java-version: 8
        architecture: x64

    - name: Maven Build
      run: mvn -B package

    # Building EaaS-base-image because it is not on DockerHub yet
    - name: Checkout EaaS-base-image
      uses: actions/checkout@v2
      with:
        repository: "ExplorViz/EaaS-base-image"
        path: "EaaS-base-image"
    - name: Build EaaS-base-image
      run: ./build-all.sh
      working-directory: EaaS-base-image

